### ISSUE TITLE
Add documentation for programming the Hacker Hotel 2024

### ISSUE THREAD

**Issue by jhaand** [badgeteam/website#108]
Observed: There is currently no documentation for the Hacker Hotel 2024 badge and how to program it. 

Expected: Instruction on how to build and upload the HH2024 firmware to the badge.
Description on which build environments can be used with the HH2024 badge with build instructions.

Will add a pointer to Hello world with ESP-IDF using Platformio.

Add documentation according this message from Renze:
if you add a folder to content/en/docs/Badges/Hackerhotel 2024 and put an _index.md file into that folder with this little header at the top of the file, followed with standard markdown then we can publish it on the website.

```
title: "Platformio for the Hackerhotel 2024 badge"
linkTitle: "Platformio"
nodateline: true
weight: 1
```

**Comment by renzenicolai** [comment]
How's this going?

**Comment by jhaand** [comment]
Finally have the time to work on this. But see the PR  #111 and issue.

**Comment by jhaand** [comment]
Documentation added with https://github.com/badgeteam/website/pull/112
