### ISSUE TITLE
Check to what extent the "Getting Started" is still relevant

### ISSUE THREAD

**Issue by a2800276** [badgeteam/website#11]
https://github.com/badgeteam/website/tree/master/content/en/docs/ESP32%20platform%20firmware/ESP32%20app%20development/Getting%20started

[rendered on the current badge.team site](https://badge.team/docs/esp32-platform-firmware/esp32-app-development/getting-started/first_egg/)

... and possibly update.

This would save duplicate effort in #3

**Comment by a2800276** [comment]
[python.zip](https://github.com/badgeteam/website/files/9038255/python.zip)


"pyrhon3 webusb_push.py python python.bin --run"

**Comment by renzenicolai** [comment]
Please keep in mind that the old platform firmware is still in use on every badge except MCH2022.

The procedure for MCH2022 is different, but keep the platform firmware pages as they are.

**Comment by a2800276** [comment]
Duplicate of #3
