### ISSUE TITLE
Error: Deprecated feature used

### ISSUE THREAD

**Issue by jhaand** [badgeteam/website#110]
Using master version of website and Hugo 0.124

Observed:
Building webserver locally fails. See logging.
[badge_website_errors.txt](https://github.com/badgeteam/website/files/14930038/badge_website_errors.txt)
Error: 
```
ERROR deprecated: config: languages.en.description: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in Hugo 0.125.0. Put the value below [languages.en.params].
```
Expected:
Building webserver locally succeeds and webserver runs.

**Comment by jhaand** [comment]
It seems the Badge.team website still runs 0.111.3 according to the CD script. https://github.com/badgeteam/website/blob/master/.github/workflows/cd.yml

If we want to onboard more people for documentation, we will need to comply to the latest edition.

**Comment by jhaand** [comment]
This page describes how to fix this.

Fixed with: https://github.com/badgeteam/website/commit/a2dcdf45f7a05b0b7ee0013d4170c50d27eacd9e

**Comment by jhaand** [comment]
Fix in https://github.com/badgeteam/website/pull/111

**Comment by renzenicolai** [comment]
Fix merged, thank you :smile:
