### ISSUE TITLE
Update CD actions to latest revisions.

### ISSUE THREAD

**Issue by jhaand** [badgeteam/website#114]
Seen after running actions for: https://github.com/badgeteam/website/pull/113

Observed:  
Running the cd.yml action currently generates the following warning.
```
build-deploy
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, SamKirkland/web-deploy@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
It seems we still use old actions that use node 16. 

Expected:  
No warnings

**Comment by pitastrudl** [comment]
We can upgrade  actions/checkout@v3 to latest, which is v4.x.x, and  SamKirkland/web-deploy@v1 seems to be not maintained anymore. As far as i've checked, the latter is just a rsync thing running in nodejs. Probably we can replace with this: https://github.com/easingthemes/ssh-deploy

That should get rid of the warning.

**Comment by jhaand** [comment]
Sounds like a good plan. Your PR already solved one thing. I look forward to the rest.

**Comment by renzenicolai** [comment]
Tested, it works 👍 

Thank you @pitastrudl for solving this issue!
