### ISSUE TITLE
description & pic of SD card holder ...

### ISSUE THREAD

**Issue by a2800276** [badgeteam/website#17]

**Comment by renzenicolai** [comment]
Very good idea. Do you need any help for this? I could take some photos if needed.

**Comment by a2800276** [comment]
... if you're bored :) I think we should be able to handle it though. 
Whoever gets around to it first, just dump them in this issue, so we don't duplicate...

**Comment by a2800276** [comment]
done, waiting for review.

https://github.com/badgeteam/website/pull/27
