### ISSUE TITLE
Connecting on Mac

### ISSUE THREAD

**Issue by obsad1an** [badgeteam/website#71]
[On this section](https://www.badge.team/docs/badges/hackerhotel-2020/connecting-mac/#connecting-to-your-badge-on-mac),  it says, "maybe install some drivers". As a beginner I would hope/expect a heads up, what kind of software I should install or what the problem could be if my badge is not being detected.

**Comment by a2800276** [comment]
The documentation is for the Hacker Hotel Badge. This Badge _should_ work on Macs. In case you continue having problems, ask in the telegram channel or come to the tent for help.

If you figured it out in the meantime we would love a pull request for the documentation!
