### ISSUE TITLE
Collect good Apps from the Hatchery for Gallery. (plus screenshots)

### ISSUE THREAD

**Issue by a2800276** [badgeteam/website#86]

**Comment by a2800276** [comment]
https://mch2022.badge.team/projects/keepnamebadgeuprightpoc2
https://mch2022.badge.team/projects/2d_ising_ferromagnet
https://mch2022.badge.team/projects/fpga_morse_144mhz
https://mch2022.badge.team/projects/badge_mouse
https://mch2022.badge.team/projects/perlin_noise
https://mch2022.badge.team/projects/pressure_graph
https://mch2022.badge.team/projects/sauna_prkl
https://mch2022.badge.team/projects/winkekatze
https://mch2022.badge.team/projects/badgemap
https://mch2022.badge.team/projects/badgeboombox
https://mch2022.badge.team/projects/gnuboy
https://mch2022.badge.team/projects/ice40_doom
https://mch2022.badge.team/projects/badgebeatbox

**Comment by a2800276** [comment]
https://github.com/hpvb/mch2022-esp32-app-sms/
MCH2022 Master System emulator
This repo contains a master system emulator for the badge. It doesn't currently have a menu or SD card driver, you have to include a game with the build.

**Comment by jhaand** [comment]
I think we can close this issue since it has become stale.
